/* eslint-env mocha */

/**
 * Integration Tests for Phase 3 → Phase 4 Flow
 *
 * Tests the integration between Visual Query Generation (Phase 3)
 * and Visual Query Execution (Phase 4).
 */

const assert = require('assert');
const { visualQueryGenerator } = require('../../services/experts/VisualQueryGenerator');
const { VisualQueryExecutor } = require('../../services/experts/VisualQueryExecutor');

describe('Phase 3 → Phase 4 Integration', () => {
    let mockVisualSearchClient;
    let executor;

    beforeEach(() => {
        // Mock Visual Search Client
        mockVisualSearchClient = {
            search: async (_params) => {
                // Mock response with bounding boxes
                return {
                    bounding_boxes: [
                        { x: 0.1, y: 0.2, width: 0.3, height: 0.05 }
                    ],
                    scores: [0.9]
                };
            },
            isAvailable: async () => true
        };

        executor = new VisualQueryExecutor(mockVisualSearchClient);
        visualQueryGenerator.resetStats();
    });

    afterEach(() => {
        executor.resetStats();
    });

    it('should execute queries generated by Phase 3', async () => {
        // Phase 3: Generate queries
        const queryGenResult = await visualQueryGenerator.generateQueries({
            extractionResults: {
                fields: [
                    { name: 'invoice_number', value: 'INV-001', confidence: 0.5 }  // Low confidence
                ]
            },
            ocrResults: { text: 'Invoice #INV-001' },
            fieldTaxonomy: {
                fields: ['invoice_number', 'invoice_date', 'total_amount']
            },
            documentMetadata: { id: 'integration-001' }
        });

        assert.ok(queryGenResult.visual_queries.length >= 3, 'Phase 3 should generate minimum 3 queries');

        // Phase 4: Execute queries
        const executionResult = await executor.executeQueries({
            visualQueries: queryGenResult.visual_queries,
            extractionResults: {
                fields: [
                    { name: 'invoice_number', value: 'INV-001', confidence: 0.5 }
                ]
            },
            documentMetadata: { id: 'integration-001' },
            documentImage: 'mock-base64-image'
        });

        assert.ok(executionResult.fields, 'Phase 4 should return merged fields');
        assert.ok(executionResult.execution_metadata, 'Phase 4 should return metadata');
        assert.ok(executionResult.execution_metadata.total_queries_executed >= 3, 'Should execute all queries');
    });

    it('should use dynamic K values based on query confidence', async () => {
        const lowConfQuery = {
            question: 'What is the invoice date?',
            field_target: 'invoice_date',
            expected_element_type: 'field_extraction',
            priority: 0.9,
            confidence: 0.3,  // Low confidence
            rarity_factor: 0.5,
            logit_bias: {}
        };

        const highConfQuery = {
            question: 'Verify invoice number',
            field_target: 'invoice_number',
            expected_element_type: 'validation',
            priority: 0.7,
            confidence: 0.95,  // High confidence
            rarity_factor: 0.1,
            logit_bias: {}
        };

        const lowK = executor._calculateDynamicK(lowConfQuery);
        const highK = executor._calculateDynamicK(highConfQuery);

        // Low confidence should result in higher K
        assert.ok(lowK > highK, 'Low confidence queries should have higher K');
    });

    it('should merge visual results with extraction results', async () => {
        const queries = [
            {
                question: 'Find the invoice number',
                field_target: 'invoice_number',
                expected_element_type: 'validation',
                priority: 0.9,
                confidence: 0.8,
                rarity_factor: 0.2,
                logit_bias: {}
            }
        ];

        // Mock Visual Search to return successful result
        mockVisualSearchClient.search = async () => ({
            bounding_boxes: [
                { x: 0.1, y: 0.2, width: 0.3, height: 0.05 }
            ],
            scores: [0.95]
        });

        const result = await executor.executeQueries({
            visualQueries: queries,
            extractionResults: {
                fields: [
                    { name: 'invoice_number', value: 'INV-001', confidence: 0.7 }
                ]
            },
            documentMetadata: { id: 'integration-002' },
            documentImage: 'mock-image'
        });

        const invoiceField = result.fields.find(f => f.name === 'invoice_number');

        assert.ok(invoiceField, 'Should have invoice_number field');
        assert.strictEqual(invoiceField.visual_confirmation, true, 'Should mark visual confirmation');
        // Confidence fusion: 0.7 * 0.6 + 0.95 * 0.4 = 0.42 + 0.38 = 0.80
        assert.ok(invoiceField.confidence > 0.79 && invoiceField.confidence < 0.81, 'Should fuse confidence scores');
    });

    it('should handle circuit breaker protection', async () => {
        // Force circuit breaker to OPEN
        executor.circuitBreaker.state = 'OPEN';

        const queries = await visualQueryGenerator.generateQueries({
            extractionResults: { fields: [] },
            ocrResults: { text: 'Sample text' },
            fieldTaxonomy: null,
            documentMetadata: { id: 'integration-003' }
        });

        const result = await executor.executeQueries({
            visualQueries: queries.visual_queries,
            extractionResults: {
                fields: [{ name: 'test_field', value: 'value', confidence: 0.8 }]
            },
            documentMetadata: { id: 'integration-003' },
            documentImage: 'mock-image'
        });

        assert.strictEqual(result.execution_metadata.fallback, true, 'Should use fallback');
        assert.strictEqual(result.execution_metadata.circuit_breaker_state, 'OPEN');
    });

    it('should deduplicate overlapping bounding boxes from multiple queries', async () => {
        const queries = [
            {
                question: 'Find invoice number',
                field_target: 'invoice_number',
                expected_element_type: 'field_extraction',
                priority: 0.9,
                confidence: 0.8,
                rarity_factor: 0.2,
                logit_bias: {}
            },
            {
                question: 'Verify invoice number',
                field_target: 'invoice_number',
                expected_element_type: 'validation',
                priority: 0.8,
                confidence: 0.9,
                rarity_factor: 0.1,
                logit_bias: {}
            }
        ];

        // Mock to return similar (overlapping) bounding boxes
        let callCount = 0;
        mockVisualSearchClient.search = async () => {
            callCount++;
            return {
                bounding_boxes: [
                    callCount === 1
                        ? { x: 0.1, y: 0.2, width: 0.3, height: 0.05 }
                        : { x: 0.11, y: 0.21, width: 0.29, height: 0.05 }  // Very similar
                ],
                scores: [callCount === 1 ? 0.9 : 0.85]
            };
        };

        const result = await executor.executeQueries({
            visualQueries: queries,
            extractionResults: { fields: [] },
            documentMetadata: { id: 'integration-004' },
            documentImage: 'mock-image'
        });

        // Should deduplicate similar boxes
        assert.ok(result.overlays.length <= 1, 'Should deduplicate overlapping boxes');
    });

    it('should create newly discovered fields from visual-only results', async () => {
        const queries = [
            {
                question: 'Find invoice date',
                field_target: 'invoice_date',
                expected_element_type: 'field_extraction',
                priority: 1.0,
                confidence: 0.9,
                rarity_factor: 0.3,
                logit_bias: {}
            }
        ];

        mockVisualSearchClient.search = async () => ({
            bounding_boxes: [
                { x: 0.3, y: 0.2, width: 0.2, height: 0.05 }
            ],
            scores: [0.88]
        });

        const result = await executor.executeQueries({
            visualQueries: queries,
            extractionResults: {
                fields: [
                    { name: 'invoice_number', value: 'INV-001', confidence: 0.9 }
                    // invoice_date NOT in extraction results
                ]
            },
            documentMetadata: { id: 'integration-005' },
            documentImage: 'mock-image'
        });

        assert.strictEqual(result.newly_discovered_fields.length, 1, 'Should have 1 newly discovered field');
        assert.strictEqual(result.newly_discovered_fields[0].name, 'invoice_date');
        assert.strictEqual(result.newly_discovered_fields[0].newly_discovered, true);
    });

    it('should calculate overlay positions for UI rendering', async () => {
        const queries = [
            {
                question: 'Find total amount',
                field_target: 'total_amount',
                expected_element_type: 'field_extraction',
                priority: 0.9,
                confidence: 0.85,
                rarity_factor: 0.2,
                logit_bias: {}
            }
        ];

        mockVisualSearchClient.search = async () => ({
            bounding_boxes: [
                { x: 0.5, y: 0.7, width: 0.2, height: 0.08 }
            ],
            scores: [0.92]
        });

        const result = await executor.executeQueries({
            visualQueries: queries,
            extractionResults: { fields: [] },
            documentMetadata: { id: 'integration-006' },
            documentImage: 'mock-image'
        });

        assert.ok(result.overlays.length > 0, 'Should have overlays');

        const overlay = result.overlays[0];
        assert.strictEqual(overlay.field_name, 'total_amount');
        assert.strictEqual(overlay.position.x, 0.5);
        assert.strictEqual(overlay.position.y, 0.7);
        assert.strictEqual(overlay.position.width, 0.2);
        assert.strictEqual(overlay.position.height, 0.08);
        assert.ok(overlay.position.x >= 0 && overlay.position.x <= 1, 'X should be normalized 0-1');
        assert.ok(overlay.position.y >= 0 && overlay.position.y <= 1, 'Y should be normalized 0-1');
    });

    it('should handle query execution failures gracefully', async () => {
        const queries = await visualQueryGenerator.generateQueries({
            extractionResults: { fields: [] },
            ocrResults: { text: 'Sample text' },
            fieldTaxonomy: null,
            documentMetadata: { id: 'integration-007' }
        });

        // Mock Visual Search to throw error
        mockVisualSearchClient.search = async () => {
            throw new Error('Sidecar unavailable');
        };

        const result = await executor.executeQueries({
            visualQueries: queries.visual_queries,
            extractionResults: {
                fields: [{ name: 'test_field', value: 'value', confidence: 0.8 }]
            },
            documentMetadata: { id: 'integration-007' },
            documentImage: 'mock-image'
        });

        // Should continue with extraction-only results
        assert.ok(result.fields.length > 0, 'Should return extraction fields');
        assert.strictEqual(result.execution_metadata.failed_queries, queries.visual_queries.length);
        assert.strictEqual(result.fields[0].visual_confirmation, false);
    });
});
